### ISSUE TITLE
After name change to App Center icon desappeared 

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#1354]

**Comment by d-loose** [comment]
Thanks - should already be fixed by https://github.com/ubuntu/app-center/commit/888baba63c222aacab4e1c2145e15ed3364601a8 in the dev branch

**Comment by alculete** [comment]
Hi @d-loose  has the update been pushed already. I still see no icon

**Comment by d-loose** [comment]
Yes, it's in latest/stable/ubuntu-23.10

**Comment by alculete** [comment]
OK, thanks. I was on edge channel
