### ISSUE TITLE
Installing the app and navigating away from the app will not allow you to see the progress again

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#1446]
Installing the app and navigating away from the window will not allow you to see the progress again

**Comment by d-loose** [comment]
Hey, this has been fixed in #1422 - for now you can now test it in the `latest/edge` channel :slightly_smiling_face:. Hope we can merge this and other bug fixes into the `latest/stable/ubuntu-23.10` channel soon!

**Comment by alculete** [comment]
changed to edge but still can't see this change.
I have just installed IntelliJ but can't see the progress after moving away from the app.

![image](https://github.com/ubuntu/app-center/assets/2129497/2374b92a-b5f1-4655-a846-3107bacd01ba)

**Comment by alculete** [comment]
Maybe my explanation was not very clear. It should have a place displaying installing or updating apps. Could be in a different menu tab or  on top of manage.

**Comment by alculete** [comment]
I think this is related to [#1438](https://github.com/ubuntu/app-center/issues/1438).
If yes you can ignore my comments on this ticket

**Comment by d-loose** [comment]
Yes correct - that's something we haven't implemented yet and I opened #1438 to keep track of that. Sorry for the misunderstanding!
