### ISSUE TITLE
Missing error handling for 'SnapdException: too many requests on ubuntu 24.04'

### ISSUE THREAD

**Issue by aimanabdul** [ubuntu/app-center#1684]
![Screenshot from 2024-06-03 14-38-06](https://github.com/ubuntu/app-center/assets/45210967/38b0203a-d1bf-41af-94ef-d36fef2630b3)

**Comment by d-loose** [comment]
Thanks for your report!
It seems like there was a temporary outage in the snap ecosystem, which should be resolved by now.
We clearly need better error handling here, though!

**Comment by d-loose** [comment]
Related (error handling): #1668

**Comment by rgborn** [comment]
This is still happening, I just got the error, SnapdException(kind: too many requests), with the same screen as above only I was doing a search.

**Comment by FemLolStudio** [comment]
Same error here too.

**Comment by d-loose** [comment]
Will be fixed by #1723
