### ISSUE TITLE
Searching the store and snapcraft.io gives differnet results 

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#1814]
Searching node on snapcraft.io
![image](https://github.com/user-attachments/assets/7022159f-2830-457b-bf4a-72e12e33a055)

Searching node on app center

![image](https://github.com/user-attachments/assets/2abdcb2e-74d1-4123-9891-73cbc42b59f9)

**Comment by d-loose** [comment]
Sounds like #1459 and #1503, which I thought was already fixed. Seems like we didn't actually add the 'wide' scope to our search here. I'll open a PR.

**Comment by alculete** [comment]
Thanks, @d-loose  I opened a new bug report because it has been a year since this was reported, closed, and not solved.

**Comment by alculete** [comment]
Hi @d-loose  I think  this solution may have brought another [issue ](https://github.com/ubuntu/app-center/issues/1816)
